name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: cd server; make test
      - name: Get release tag
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./server/
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/stencil:latest
            docker.pkg.github.com/${{ github.repository }}/stencil:${{ steps.get_version.outputs.version-without-v }}
            odpf/stencil:latest
            odpf/stencil:${{ steps.get_version.outputs.version-without-v }}
